/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codename1.webrtc;

/**
 * The WebRTC API's RTCIceCandidateInit dictionary, which contains the
 * information needed to fundamentally describe an RTCIceCandidate.
 * RTCIceCandidateInit is used when using new RTCIceCandidate() to create a new
 * ICE candidate object. It's also used as the return value from the
 * RTCIceCandidate.toJSON() method, and can be passed directly into
 * RTCPeerConnection.addIceCandidate() to add a candidate to the peer
 * connection.
 *
 * @author shannah
 * @see https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateInit
 */
public class RTCIceCandidateInit {

    private String candidate;
    private String sdpMid;
    private Integer sdpMLineIndex;
    private String usernameFragment;

    /**
     * A DOMString containing a string which uniquely identifies the remote
     * peer. This string is generated by WebRTC at the beginning of the session,
     * and at least 24 bits worth of the string contain random data. The string
     * may be up to 256 characters long. This property has no default value and
     * is not present unless set explicitly.
     *
     * @return the usernameFragment
     * @see
     * https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateInit/usernameFragment
     */
    public String getUsernameFragment() {
        return usernameFragment;
    }

    /**
     * A DOMString containing a string which uniquely identifies the remote
     * peer. This string is generated by WebRTC at the beginning of the session,
     * and at least 24 bits worth of the string contain random data. The string
     * may be up to 256 characters long. This property has no default value and
     * is not present unless set explicitly.
     *
     * @param usernameFragment the usernameFragment to set
     * @see
     * https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateInit/usernameFragment
     */
    public void setUsernameFragment(String usernameFragment) {
        this.usernameFragment = usernameFragment;
    }

    /**
     * The ICE candidate-attribute. If the candidate is an indicator that there
     * are no further candidates (rather than representing a new candidate),
     * this is the empty string (""). The default is the empty string.
     *
     * @return the candidate
     * @see
     * https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateInit/candidate
     */
    public String getCandidate() {
        return candidate;
    }

    /**
     * The ICE candidate-attribute. If the candidate is an indicator that there
     * are no further candidates (rather than representing a new candidate),
     * this is the empty string (""). The default is the empty string.
     *
     * @param candidate the candidate to set
     * @see
     * https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateInit/candidate
     */
    public void setCandidate(String candidate) {
        this.candidate = candidate;
    }

    /**
     * The identification tag of the media stream with which the candidate is
     * associated, or null if there is no associated media stream. The default
     * is null.
     *
     * @return the sdpMid
     * @see
     * https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateInit/sdpMid
     */
    public String getSdpMid() {
        return sdpMid;
    }

    /**
     * The identification tag of the media stream with which the candidate is
     * associated, or null if there is no associated media stream. The default
     * is null.
     *
     * @param sdpMid the sdpMid to set
     * @see
     * https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateInit/sdpMid
     */
    public void setSdpMid(String sdpMid) {
        this.sdpMid = sdpMid;
    }

    /**
     * The zero-based index of the m-line within the SDP of the media
     * description with which the candidate is associated, or null if no such
     * associated exists. The default is null.
     *
     * @return the sdpMLineIndex
     * @see
     * https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateInit/sdpMLineIndex
     */
    public Integer getSdpMLineIndex() {
        return sdpMLineIndex;
    }

    /**
     * The zero-based index of the m-line within the SDP of the media
     * description with which the candidate is associated, or null if no such
     * associated exists. The default is null.
     *
     * @param sdpMLineIndex the sdpMLineIndex to set
     * @seew
     * https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateInit/sdpMLineIndex
     */
    public void setSdpMLineIndex(Integer sdpMLineIndex) {
        this.sdpMLineIndex = sdpMLineIndex;
    }
}
